---
abstract: 'XS Version of Marpa'
author:
  - 'Jeffrey Kegler'
build_requires:
  ExtUtils::CBuilder: 0.27
  Test::More: 0.94
configure_requires:
  ExtUtils::PkgConfig: 1.12
  Glib: 1.223
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marpa-XS
no_index:
  directory:
    - pperl
    - config
    - inc
    - tool
    - t
    - html
    - devlib
    - libmarpa
    - author.t
  namespace:
    - Marpa::XS::Recognizer
    - Marpa::XS::Grammar
    - Marpa::XS::Value
    - Marpa::XS::Perl
    - Marpa::XS::Test
    - Marpa::XS::Display
    - Marpa::XS::Internal
  package:
    - Marpa::XS::Value
    - Marpa::XS::Perl
    - Marpa::XS::Test
    - Marpa::XS::Display
    - Marpa::XS::Internal
provides:
  Marpa::XS:
    file: lib/Marpa/XS.pm
    version: 1.007_000
  Marpa::XS::Grammar:
    file: lib/Marpa/XS/Grammar.pm
    version: 1.007_000
  Marpa::XS::Internal:
    file: lib/Marpa/XS/Internal.pm
    version: 1.007_000
  Marpa::XS::Internal::Grammar:
    file: lib/Marpa/XS/Grammar.pm
    version: 0
  Marpa::XS::Internal::Recognizer:
    file: lib/Marpa/XS/Value.pm
    version: 0
  Marpa::XS::Internal::Value:
    file: lib/Marpa/XS/Value.pm
    version: 0
  Marpa::XS::Recognizer:
    file: lib/Marpa/XS/Recognizer.pm
    version: 1.007_000
  Marpa::XS::Value:
    file: lib/Marpa/XS/Value.pm
    version: 1.007_000
recommends:
  PPI: 1.206
  Test::Weaken: 3.004000
requires:
  Carp: 1.08
  Data::Dumper: 2.125
  ExtUtils::PkgConfig: 1.12
  Glib: 1.223
  List::Util: 1.21
  Scalar::Util: 1.21
  Task::Weaken: 0
resources:
  repository: git://github.com/jeffreykegler/Marpa-XS.git
version: 1.007_000
